[package]
name = "musath"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
clap = { version = "4.5.57", features = ["derive"] }
hound = "3.5.1"
lazy_static = "1.5.0"
pest = "2.8.6"
pest_derive = { version = "2.8.6", features = ["grammar-extras"] }
